### ISSUE TITLE
DCPAM aquaplanet example does not run in mint21

### ISSUE THREAD

**Issue by oculus99** [ywkawai/DCPCM#1]
This example compiles, but does not run in Linux mint. Held-Suarez example runs OK.

https://www.gfd-dennou.org/library/dcpam/dcpam5/dcpam5-git/doc/gokuraku/exp-APE-NH00.htm.en

DCPAM generates error, when i try run aquaplanet example.

~/dcpam5-exp/ape-nh00-exp

Held-Suarez example run is OK.

All DCPAM "GOKURAKU" examples, that have netcdf reading, does fail.

My OS is Mint 20.2 Uma 64-bit. I use "buster repos". 
I dont compile any libs myself.

 
deb http://www.gfd-dennou.org/library/cc-env/Linux/debian-dennou buster main
 deb-src http://www.gfd-dennou.org/library/cc-env/Linux/debian-dennou buster main

Last messages from run:

 *** MESSAGE [HistoryCreate1] ***  "SnowLsc.nc" is created (origin=0. [day])
 *** MESSAGE [HistoryCreate1] ***  "PRCPLsc.nc" is created (origin=0. [day])
 *** MESSAGE [HistoryCreate1] ***  "SeaIceConc.nc" is created (origin=0. [day])
 *** MESSAGE [HistoryCreate1] ***  "SurfAlbedo.nc" is created (origin=0. [day])
 *** WARNING [HistoryAutoAllVarFix] ***  names "O3,CO2" from NAMELIST "gtool_historyauto_nml" are invalid.
 *** ERROR (Code -506) [HistoryAutoAllVarFix] ***   variable name (O3,CO2) is invalid

Program aborted. Backtrace:
#0  0x7fbd2b096d21 in ???
#1  0x7fbd2b0977ad in ???
#2  0x7fbd2b2eb38c in ???
#3  0x556e0980902c in ???
#4  0x556e09775c87 in ???
#5  0x556e0976ff69 in ???
#6  0x556e094a5b41 in dcpam_main
      at /home/mint/dcpam5-git/src/main/dcpam_main.f90:2899
#7  0x556e0949a7fe in main
      at /home/mint/dcpam5-git/src/main/dcpam_main.f90:29

**Comment by ywkawai** [comment]
Sorry, this repository is not for DCPAM. Thus, I close this issue.
